####################################################
#
# Welcome to Bizzcon Jekyll Template
#
# Product Link : https://themeix.com/product/bizzcon-jekyll-template/
# Version : v1.0.0 ( Github Pages Version )
#
####################################################

# Site settings
title                   : "AinoA Cloud Solutions &bull; Azure training & consultancy"
SEOTitle                : "AinoA Cloud Solutions &bull; Azure training & consultancy"
header-img              : img/home-bg.jpg
email                   : "themeix@gmail.com"
description             : "Azure bestaat uit een uitgebreide set cloudservices waarmee ontwikkelaars en IT-professionals toepassingen bouwen, implementeren en beheren in een wereldwijde netwerk van datacenters."
keyword: "Azure"
url                     : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                 : # the subpath of your site, e.g. "/blog"
logo_url                : /assets/images/logo.png
logo_url_white          : /assets/images/logo-white.png
footer_logo_url: /assets/images/logo.png

mailclimp_url           : 
dribble_url             :  
facebook_url            :  
instagram_url           : 
youtube_url             : 
twitter_url             : 
linkedin_url            : 
pinterest_url           : 


# Build settings
permalink: /:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives



jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'
    
 
collections:
  authors:
    output: true
    permalink: /author/:path/
  services:
    output: true
    permalink: /service/:path/
  teams:
    output: true
    permalink: /team/:path/
    
feed:
  collections:
    posts:
      path: "/index.xml"
     
theme: jekyll-theme-minimal
