url: http://test.ainoacloud.com
name: Ainoa cloud solutions
description: Azure training and consultancy

theme: jekyll-theme-cayman
remote_theme: mmistakes/minimal-mistakes
google_analytics: UA-163618858-1
