url: http://test.ainoacloud.com
name: Ainoa cloud solutions
description: Azure training and consultancy

plugins:
  - jekyll-remote-theme

theme: mmistakes/minimal-mistakes

google_analytics: UA-163618858-1
